name: pureplay
description: "PurePlay - a fast, offline local video and audio player for Android."
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit: 1.2.6
  media_kit_video: 2.0.1
  media_kit_libs_video: ^1.0.7
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.6
  audio_service: ^0.18.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/28410075-7c95-4b5e-a608-834b19e5baa1.jpg
    - assets/3ca7ffd9-474a-495e-a2e2-2df430d09e63.jpg
    - assets/7bd08913-9bd7-485f-bf3f-2714543a41b8.jpg

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#160B35"
  adaptive_icon_foreground: "assets/logo.png"
